### ISSUE TITLE
iOS版本上线疑问？

### ISSUE THREAD

**Issue by shijian123** [1c7/CrashCourse-Chinese-ReactNative-App#1]
如果仅仅因为没有苹果账户的话，我可以提供

**Comment by 1c7** [comment]
@shijian123 感谢热心想帮忙。

苹果账号只是其中一个障碍，其实之前我找过其他朋友，账号是拿得到的。
现在的问题是我没有时间，最近工作挺忙的，我没空去倒腾 RN 打包 iOS。
上次我打包的时候貌似还非要我弄个真机还是咋回事（XCode 里）挺久之前的事情了。
我现在手头有一个 Macbook Pro，但是没有 iPhone（在用一加6T）

之前没弄成功后来就算了，一直没弄，拖着。直到现在你提了这个问题。
那我看看接下来1-2周有没有办法弄弄，哪怕提交之后被拒，起码也试过了对吧~

如果有困难我没法解决再主动找朋友帮忙~
谢谢提议

**Comment by 1c7** [comment]
我先 close 掉这个 issue 好了。
现在2018年12月12号了。我看看在2019年1月1号之前有没有办法抽时间把这个搞定。提交一次。被拒的话就算了。最近苹果审核挺严的。
